- name: Setup RoboShop
  hosts: FRONTEND
  become: yes
  roles:
    - frontend
    - elk

- name: Setup RoboShop
  hosts: MONGODB
  become: yes
  roles:
    - mongodb

- name: Setup RoboShop
  hosts: CATALOGUE
  become: yes
  roles:
    - catalogue
    - elk

- name: Setup RoboShop
  hosts: REDIS
  become: yes
  roles:
    - redis

- name: Setup RoboShop
  hosts: USER
  become: yes
  roles:
    - user
    - elk

- name: Setup RoboShop
  hosts: MYSQL
  become: yes
  roles:
    - mysql

- name: Setup RoboShop
  hosts: SHIPPING
  become: yes
  roles:
    - shipping
    - elk

- name: Setup RoboShop
  hosts: RABBITMQ
  become: yes
  roles:
    - rabbitmq

- name: Setup RoboShop
  hosts: PAYMENT
  become: yes
  roles:
    - payment
    - elk

- name: Setup RoboShop
  hosts: CART
  become: yes
  roles:
    - cart