- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Download frontend content
  ansible.builtin.get_url:
    url: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp/frontend.zip

- name: Recursively old html content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Unarchive frontend file
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Copy frontend content to nginx
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes

