- name: copy logstash config
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted

- name: wait for logstash to start
  wait_for:
    port: 5044
    timeout: 180
    delay: 30